version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ueda-sam-swagger"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-t3smooly3wwi"
s3_prefix = "ueda-sam-swagger"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
