basePath: /
definitions:
  handler.Message:
    properties:
      message:
        type: string
    type: object
  handler.TodoDTO:
    properties:
      description:
        example: 部屋とお風呂
        type: string
      id:
        example: 1
        type: integer
      name:
        example: 掃除
        type: string
      status:
        enum:
        - new
        - wip
        - todo
        example: new
        type: string
    type: object
  handler.TodoForm:
    properties:
      description:
        example: 部屋とお風呂
        type: string
      name:
        example: 掃除
        type: string
      status:
        enum:
        - new
        - wip
        - todo
        example: new
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a Todo-app server.
  title: Todo API
  version: "1.0"
paths:
  /todo:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.TodoDTO'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Message'
      summary: Get all todo
      tags:
      - todo
    post:
      consumes:
      - application/json
      parameters:
      - description: new todo
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/handler.TodoForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.TodoDTO'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Message'
      summary: Add a todo
      tags:
      - todo
  /todo/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id of todo to remove
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Message'
      summary: Remove a todo
      tags:
      - todo
    put:
      consumes:
      - application/json
      parameters:
      - description: edited todo
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/handler.TodoForm'
      - description: id of todo to edit
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.TodoDTO'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Message'
      summary: Edit a todo
      tags:
      - todo
swagger: "2.0"
